apiVersion: v1
kind: PersistentVolume
metadata:
  name: littlebook-mysql-pvc
spec:
  storageClassName: trunk
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"